const gatJson = [
    {
        "ID": 37057,
        "Name": "HTTP Methods Allowed (per directory)",
        "Description": "\\nBy calling the OPTIONS method it is possible to determine which HTTP methods are allowed on each directory. \\n\\nAs this list may be incomplete the plugin also tests - if 'Thorough tests' are enabled or 'Enable web applications tests' is set to 'yes' in the scan policy - various known HTTP methods on each directory and considers them as unsupported if it receives a response code of 400 403 405 or 501. \\n\\nNote that the plugin output is only informational and does not necessarily indicate the presence of any security vulnerabilities.",
        "Asset": "10.15.0.112",
        "Status": "PENDING",
        "Severity (Asset risk)": "INFORMATIVE",
        "Responsible": "Raphael Pinheiro",
        "Port": 2381,
        "Protocol": "tcp",
        "Service name": "www",
        "Source": "SCAN",
        "Changed date": "11/01/2017-19:31:07",
        "Last seen date": "08/06/2016-18:37:36",
        "Due date": "27/02/2019-23:00:00",
        "Tags": "HTTP",
        "KB": "HTTP Methods Allowed (per directory)",
        "Recommendations": "",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37055,
        "Name": "SSL Certificate Information",
        "Description": "\\nThis plugin connects to every SSL-related port and attempts to extract and dump the X.509 certificate.",
        "Asset": "10.15.0.126",
        "Status": "PENDING",
        "Severity (Asset risk)": "LOW",
        "Responsible": "Starlin",
        "Port": 2381,
        "Protocol": "tcp",
        "Service name": "www",
        "Source": "MANUAL",
        "Changed date": "16/01/2017-19:31:08",
        "Last seen date": "08/06/2016-19:44:25",
        "Due date": "27/02/2019-23:00:01",
        "Tags": "SSL",
        "KB": "SSL Certificate Information",
        "Recommendations": "",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37054,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.14",
        "Status": "REOPENED",
        "Severity (Asset risk)": "HIGH",
        "Responsible": "Leonardo Brancalhão",
        "Port": 135,
        "Protocol": "tcp",
        "Service name": "epmap",
        "Source": "CHECKLIST",
        "Changed date": "11/04/2017-19:31:09",
        "Last seen date": "08/06/2016-14:05:19",
        "Due date": "27/02/2019-23:00:02",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37053,
        "Name": "RPC Services Enumeration",
        "Description": "\\nBy sending a DUMP request to the portmapper it was possible to enumerate the ONC RPC services running on the remote port.  Using this information it is possible to connect and bind to each service by sending an RPC request to the remote port.",
        "Asset": "10.15.0.54",
        "Status": "PENDING",
        "Severity (Asset risk)": "LOW",
        "Responsible": "Diego",
        "Port": 2049,
        "Protocol": "udp",
        "Service name": "rpc-200006",
        "Source": "CHECKLIST",
        "Changed date": "11/01/2018-19:31:10",
        "Last seen date": "08/06/2016-16:56:36",
        "Due date": "27/02/2019-23:00:03",
        "Tags": "RPC",
        "KB": "RPC Services Enumeration",
        "Recommendations": "",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37052,
        "Name": "SSH Protocol Versions Supported",
        "Description": "\\nThis plugin determines the versions of the SSH protocol supported by the remote SSH daemon.",
        "Asset": "10.15.0.182",
        "Status": "FIXED",
        "Severity (Asset risk)": "INFORMATIVE",
        "Responsible": "Thiago",
        "Port": 22,
        "Protocol": "tcp",
        "Service name": "ssh",
        "Source": "CHECKLIST",
        "Changed date": "01/01/2018-19:31:11",
        "Last seen date": "08/06/2016-20:48:25",
        "Due date": "07/02/2019-23:00:04",
        "Tags": "SSH; Protocol",
        "KB": "SSH Protocol Versions Supported",
        "Recommendations": "",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37051,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.125",
        "Status": "ACCEPTED",
        "Severity (Asset risk)": "CRITICAL",
        "Responsible": "Fernanda",
        "Port": 135,
        "Protocol": "tcp",
        "Service name": "epmap",
        "Source": "CHECKLIST",
        "Changed date": "11/03/2018-19:31:12",
        "Last seen date": "08/06/2016-19:36:34",
        "Due date": "07/02/2019-23:00:05",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37050,
        "Name": "Nessus SNMP Scanner",
        "Description": "\\nThis plugin runs an SNMP scan against the remote machine to find open ports.\\n\\nSee the section 'plugins options' to configure it.",
        "Asset": "10.15.0.113",
        "Status": "PENDING",
        "Severity (Asset risk)": "CRITICAL",
        "Responsible": "Raphael Pinheiro",
        "Port": 161,
        "Protocol": "tcp",
        "Service name": "snmp",
        "Source": "MANUAL",
        "Changed date": "11/06/2018-19:31:13",
        "Last seen date": "08/06/2016-18:43:56",
        "Due date": "07/02/2019-23:00:06",
        "Tags": "SNMP",
        "KB": "Nessus SNMP Scanner",
        "Recommendations": "",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37049,
        "Name": "Microsoft Windows SMB Registry : Nessus Cannot Access the Windows Registry",
        "Description": "\\nIt was not possible to connect to PIPE\\\\winreg on the remote host.\\n\\nIf you intend to use Nessus to perform registry-based checks the registry checks will not work because the 'Remote Registry Access' service (winreg) has been disabled on the remote host or can not be connected to with the supplied credentials.",
        "Asset": "10.15.0.145",
        "Status": "IN RETEST",
        "Severity (Asset risk)": "LOW",
        "Responsible": "Diego",
        "Port": 445,
        "Protocol": "tcp",
        "Service name": "cifs",
        "Source": "SCAN",
        "Changed date": "11/07/2018-19:31:14",
        "Last seen date": "08/06/2016-20:28:45",
        "Due date": "07/02/2019-23:00:07",
        "Tags": "Microsoft",
        "KB": "Microsoft Windows SMB Registry : Nessus Cannot Access the Windows Registry",
        "Recommendations": "",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37048,
        "Name": "SSL Certificate Cannot Be Trusted",
        "Description": "\\nThe server's X.509 certificate cannot be trusted. This situation can occur in three different ways in which the chain of trust can be broken as stated below :\\n\\n  - First the top of the certificate chain sent by the     server might not be descended from a known public     certificate authority. This can occur either when the     top of the chain is an unrecognized self-signed     certificate or when intermediate certificates are     missing that would connect the top of the certificate     chain to a known public certificate authority.\\n\\n  - Second the certificate chain may contain a certificate     that is not valid at the time of the scan. This can     occur either when the scan occurs before one of the     certificate's 'notBefore' dates or after one of the     certificate's 'notAfter' dates.\\n\\n  - Third the certificate chain may contain a signature     that either didn't match the certificate's information     or could not be verified. Bad signatures can be fixed by     getting the certificate with the bad signature to be     re-signed by its issuer. Signatures that could not be     verified are the result of the certificate's issuer     using a signing algorithm that Nessus either does not     support or does not recognize.\\n\\nIf the remote host is a public host in production any break in the chain makes it more difficult for users to verify the authenticity and identity of the web server. This could make it easier to carry out man-in-the-middle attacks against the remote host.",
        "Asset": "10.15.0.126",
        "Status": "PENDING",
        "Severity (Asset risk)": "INFORMATIVE",
        "Responsible": "Thiago",
        "Port": 3389,
        "Protocol": "tcp",
        "Service name": "msrdp",
        "Source": "SCAN",
        "Changed date": "11/01/2018-19:31:15",
        "Last seen date": "08/06/2016-19:44:25",
        "Due date": "17/01/2019-23:00:08",
        "Tags": "SSL",
        "KB": "SSL Certificate Cannot Be Trusted",
        "Recommendations": "\\nPurchase or generate a proper certificate for this service.\\n",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37047,
        "Name": "SSL Certificate Cannot Be Trusted",
        "Description": "\\nThe server's X.509 certificate cannot be trusted. This situation can occur in three different ways in which the chain of trust can be broken as stated below :\\n\\n  - First the top of the certificate chain sent by the     server might not be descended from a known public     certificate authority. This can occur either when the     top of the chain is an unrecognized self-signed     certificate or when intermediate certificates are     missing that would connect the top of the certificate     chain to a known public certificate authority.\\n\\n  - Second the certificate chain may contain a certificate     that is not valid at the time of the scan. This can     occur either when the scan occurs before one of the     certificate's 'notBefore' dates or after one of the     certificate's 'notAfter' dates.\\n\\n  - Third the certificate chain may contain a signature     that either didn't match the certificate's information     or could not be verified. Bad signatures can be fixed by     getting the certificate with the bad signature to be     re-signed by its issuer. Signatures that could not be     verified are the result of the certificate's issuer     using a signing algorithm that Nessus either does not     support or does not recognize.\\n\\nIf the remote host is a public host in production any break in the chain makes it more difficult for users to verify the authenticity and identity of the web server. This could make it easier to carry out man-in-the-middle attacks against the remote host.",
        "Asset": "10.15.0.15",
        "Status": "IN TREATMENT",
        "Severity (Asset risk)": "HIGH",
        "Responsible": "Fernanda",
        "Port": 3389,
        "Protocol": "tcp",
        "Service name": "msrdp",
        "Source": "SCAN",
        "Changed date": "11/11/2018-19:31:16",
        "Last seen date": "08/06/2016-14:20:00",
        "Due date": "17/01/2019-23:00:09",
        "Tags": "SSL",
        "KB": "SSL Certificate Cannot Be Trusted",
        "Recommendations": "\\nPurchase or generate a proper certificate for this service.\\n",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37046,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.40",
        "Status": "NON EXISTENT",
        "Severity (Asset risk)": "MEDIUM",
        "Responsible": "Raphael Pinheiro",
        "Port": 3389,
        "Protocol": "tcp",
        "Service name": "msrdp",
        "Source": "SCAN",
        "Changed date": "11/06/2018-19:31:17",
        "Last seen date": "08/06/2016-15:49:33",
        "Due date": "17/01/2019-23:00:10",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37045,
        "Name": "Microsoft Windows SMB Service Detection",
        "Description": "\\nThe remote service understands the CIFS (Common Internet File System) or Server Message Block (SMB) protocol used to provide shared access to files printers etc between nodes on a network.",
        "Asset": "10.15.0.45",
        "Status": "ACCEPTED",
        "Severity (Asset risk)": "LOW",
        "Responsible": "Starlin",
        "Port": 139,
        "Protocol": "tcp",
        "Service name": "smb",
        "Source": "SCAN",
        "Changed date": "21/01/2018-19:31:18",
        "Last seen date": "08/06/2016-16:08:15",
        "Due date": "17/01/2019-23:00:11",
        "Tags": "Microsoft; SMB",
        "KB": "Microsoft Windows SMB Service Detection",
        "Recommendations": "",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37044,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.19",
        "Status": "REOPENED",
        "Severity (Asset risk)": "MEDIUM",
        "Responsible": "Raphael Pinheiro",
        "Port": 80,
        "Protocol": "tcp",
        "Service name": "www",
        "Source": "SCAN",
        "Changed date": "12/01/2018-19:31:19",
        "Last seen date": "08/06/2016-14:44:25",
        "Due date": "17/01/2019-23:00:12",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37043,
        "Name": "SSL Certificate Information",
        "Description": "\\nThis plugin connects to every SSL-related port and attempts to extract and dump the X.509 certificate.",
        "Asset": "10.15.0.133",
        "Status": "IN RETEST",
        "Severity (Asset risk)": "CRITICAL",
        "Responsible": "Starlin",
        "Port": 48007,
        "Protocol": "tcp",
        "Service name": "unknown",
        "Source": "SCAN",
        "Changed date": "01/01/2018-19:31:20",
        "Last seen date": "08/06/2016-20:33:03",
        "Due date": "17/01/2019-23:00:13",
        "Tags": "SSL",
        "KB": "SSL Certificate Information",
        "Recommendations": "",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37042,
        "Name": "Service Detection",
        "Description": "\\nNessus was able to identify the remote service by its banner or by looking at the error message it sends when it receives an HTTP request.",
        "Asset": "10.15.0.23",
        "Status": "NON EXISTENT",
        "Severity (Asset risk)": "HIGH",
        "Responsible": "Starlin",
        "Port": 3872,
        "Protocol": "tcp",
        "Service name": "www",
        "Source": "SCAN",
        "Changed date": "11/03/2018-19:31:21",
        "Last seen date": "08/06/2016-22:08:39",
        "Due date": "17/01/2019-23:00:14",
        "Tags": "Service",
        "KB": "Service Detection",
        "Recommendations": "",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37041,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.15",
        "Status": "ACCEPTED",
        "Severity (Asset risk)": "INFORMATIVE",
        "Responsible": "Starlin",
        "Port": 135,
        "Protocol": "tcp",
        "Service name": "epmap",
        "Source": "SCAN",
        "Changed date": "11/05/2018-19:31:22",
        "Last seen date": "08/06/2016-14:20:00",
        "Due date": "11/03/2019-23:00:15",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37040,
        "Name": "SSL Certificate Cannot Be Trusted",
        "Description": "\\nThe server's X.509 certificate cannot be trusted. This situation can occur in three different ways in which the chain of trust can be broken as stated below :\\n\\n  - First the top of the certificate chain sent by the     server might not be descended from a known public     certificate authority. This can occur either when the     top of the chain is an unrecognized self-signed     certificate or when intermediate certificates are     missing that would connect the top of the certificate     chain to a known public certificate authority.\\n\\n  - Second the certificate chain may contain a certificate     that is not valid at the time of the scan. This can     occur either when the scan occurs before one of the     certificate's 'notBefore' dates or after one of the     certificate's 'notAfter' dates.\\n\\n  - Third the certificate chain may contain a signature     that either didn't match the certificate's information     or could not be verified. Bad signatures can be fixed by     getting the certificate with the bad signature to be     re-signed by its issuer. Signatures that could not be     verified are the result of the certificate's issuer     using a signing algorithm that Nessus either does not     support or does not recognize.\\n\\nIf the remote host is a public host in production any break in the chain makes it more difficult for users to verify the authenticity and identity of the web server. This could make it easier to carry out man-in-the-middle attacks against the remote host.",
        "Asset": "10.15.0.23",
        "Status": "PENDING",
        "Severity (Asset risk)": "INFORMATIVE",
        "Responsible": "",
        "Port": 4903,
        "Protocol": "tcp",
        "Service name": "www",
        "Source": "CHECKLIST",
        "Changed date": "11/01/2018-19:31:23",
        "Last seen date": "08/06/2016-22:08:39",
        "Due date": "11/03/2019-23:00:16",
        "Tags": "SSL",
        "KB": "SSL Certificate Cannot Be Trusted",
        "Recommendations": "\\nPurchase or generate a proper certificate for this service.\\n",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37039,
        "Name": "SSL Certificate Information",
        "Description": "\\nThis plugin connects to every SSL-related port and attempts to extract and dump the X.509 certificate.",
        "Asset": "10.15.0.16",
        "Status": "PENDING",
        "Severity (Asset risk)": "INFORMATIVE",
        "Responsible": "",
        "Port": 2381,
        "Protocol": "tcp",
        "Service name": "www",
        "Source": "CHECKLIST",
        "Changed date": "11/01/2018-19:31:24",
        "Last seen date": "08/06/2016-14:30:14",
        "Due date": "11/03/2019-23:00:17",
        "Tags": "SSL",
        "KB": "SSL Certificate Information",
        "Recommendations": "",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37038,
        "Name": "HTTP Methods Allowed (per directory)",
        "Description": "\\nBy calling the OPTIONS method it is possible to determine which HTTP methods are allowed on each directory. \\n\\nAs this list may be incomplete the plugin also tests - if 'Thorough tests' are enabled or 'Enable web applications tests' is set to 'yes' in the scan policy - various known HTTP methods on each directory and considers them as unsupported if it receives a response code of 400 403 405 or 501. \\n\\nNote that the plugin output is only informational and does not necessarily indicate the presence of any security vulnerabilities.",
        "Asset": "10.15.0.111",
        "Status": "PENDING",
        "Severity (Asset risk)": "INFORMATIVE",
        "Responsible": "",
        "Port": 2381,
        "Protocol": "tcp",
        "Service name": "www",
        "Source": "SCAN",
        "Changed date": "19/07/2018-19:31:25",
        "Last seen date": "08/06/2016-18:36:55",
        "Due date": "11/03/2019-23:00:18",
        "Tags": "HTTP",
        "KB": "HTTP Methods Allowed (per directory)",
        "Recommendations": "",
        "Root cause": "Generic  ",
        
    },
    {
        "ID": 37037,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.124",
        "Status": "PENDING",
        "Severity (Asset risk)": "INFORMATIVE",
        "Responsible": "",
        "Port": 135,
        "Protocol": "tcp",
        "Service name": "epmap",
        "Source": "SCAN",
        "Changed date": "17/01/2018-19:31:26",
        "Last seen date": "08/06/2016-19:34:56",
        "Due date": "11/03/2019-23:00:19",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "Root cause": "Generic  ",
        
    }
];

export default gatJson;
