const gatJson = [
    {
        "ID": 37057,
        "Name": "HTTP Methods Allowed (per directory)",
        "Description": "\\nBy calling the OPTIONS method it is possible to determine which HTTP methods are allowed on each directory. \\n\\nAs this list may be incomplete the plugin also tests - if 'Thorough tests' are enabled or 'Enable web applications tests' is set to 'yes' in the scan policy - various known HTTP methods on each directory and considers them as unsupported if it receives a response code of 400 403 405 or 501. \\n\\nNote that the plugin output is only informational and does not necessarily indicate the presence of any security vulnerabilities.",
        "Asset": "10.15.0.112",
        "Status": "PENDING",
        "Severity": "INFORMATIVE",
        "Responsible": "Raphael Pinheiro",
        "Port": 2381,
        "Protocol": "tcp",
        "ServiceName": "www",
        "Source": "SCAN",
        "ChangedDate": "11/01/2017-19:31:07",
        "LastSeenDate": "08/06/2016-18:37:36",
        "DueDate": "27/02/2019-23:00:00",
        "Tags": "HTTP",
        "KB": "HTTP Methods Allowed (per directory)",
        "Recommendations": "",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37055,
        "Name": "SSL Certificate Information",
        "Description": "\\nThis plugin connects to every SSL-related port and attempts to extract and dump the X.509 certificate.",
        "Asset": "10.15.0.126",
        "Status": "PENDING",
        "Severity": "LOW",
        "Responsible": "Starlin",
        "Port": 2381,
        "Protocol": "tcp",
        "ServiceName": "www",
        "Source": "MANUAL",
        "ChangedDate": "16/01/2017-19:31:08",
        "LastSeenDate": "08/06/2016-19:44:25",
        "DueDate": "27/02/2019-23:00:01",
        "Tags": "SSL",
        "KB": "SSL Certificate Information",
        "Recommendations": "",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37054,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.14",
        "Status": "REOPENED",
        "Severity": "HIGH",
        "Responsible": "Leonardo Brancalhão",
        "Port": 135,
        "Protocol": "tcp",
        "ServiceName": "epmap",
        "Source": "CHECKLIST",
        "ChangedDate": "11/04/2017-19:31:09",
        "LastSeenDate": "08/06/2016-14:05:19",
        "DueDate": "27/02/2019-23:00:02",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37053,
        "Name": "RPC Services Enumeration",
        "Description": "\\nBy sending a DUMP request to the portmapper it was possible to enumerate the ONC RPC services running on the remote port.  Using this information it is possible to connect and bind to each service by sending an RPC request to the remote port.",
        "Asset": "10.15.0.54",
        "Status": "PENDING",
        "Severity": "LOW",
        "Responsible": "Diego",
        "Port": 2049,
        "Protocol": "udp",
        "ServiceName": "rpc-200006",
        "Source": "CHECKLIST",
        "ChangedDate": "11/01/2018-19:31:10",
        "LastSeenDate": "08/06/2016-16:56:36",
        "DueDate": "27/02/2019-23:00:03",
        "Tags": "RPC",
        "KB": "RPC Services Enumeration",
        "Recommendations": "",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37052,
        "Name": "SSH Protocol Versions Supported",
        "Description": "\\nThis plugin determines the versions of the SSH protocol supported by the remote SSH daemon.",
        "Asset": "10.15.0.182",
        "Status": "FIXED",
        "Severity": "INFORMATIVE",
        "Responsible": "Thiago",
        "Port": 22,
        "Protocol": "tcp",
        "ServiceName": "ssh",
        "Source": "CHECKLIST",
        "ChangedDate": "01/01/2018-19:31:11",
        "LastSeenDate": "08/06/2016-20:48:25",
        "DueDate": "07/02/2019-23:00:04",
        "Tags": "SSH; Protocol",
        "KB": "SSH Protocol Versions Supported",
        "Recommendations": "",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37051,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.125",
        "Status": "ACCEPTED",
        "Severity": "CRITICAL",
        "Responsible": "Fernanda",
        "Port": 135,
        "Protocol": "tcp",
        "ServiceName": "epmap",
        "Source": "CHECKLIST",
        "ChangedDate": "11/03/2018-19:31:12",
        "LastSeenDate": "08/06/2016-19:36:34",
        "DueDate": "07/02/2019-23:00:05",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37050,
        "Name": "Nessus SNMP Scanner",
        "Description": "\\nThis plugin runs an SNMP scan against the remote machine to find open ports.\\n\\nSee the section 'plugins options' to configure it.",
        "Asset": "10.15.0.113",
        "Status": "PENDING",
        "Severity": "CRITICAL",
        "Responsible": "Raphael Pinheiro",
        "Port": 161,
        "Protocol": "tcp",
        "ServiceName": "snmp",
        "Source": "MANUAL",
        "ChangedDate": "11/06/2018-19:31:13",
        "LastSeenDate": "08/06/2016-18:43:56",
        "DueDate": "07/02/2019-23:00:06",
        "Tags": "SNMP",
        "KB": "Nessus SNMP Scanner",
        "Recommendations": "",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37049,
        "Name": "Microsoft Windows SMB Registry : Nessus Cannot Access the Windows Registry",
        "Description": "\\nIt was not possible to connect to PIPE\\\\winreg on the remote host.\\n\\nIf you intend to use Nessus to perform registry-based checks the registry checks will not work because the 'Remote Registry Access' service (winreg) has been disabled on the remote host or can not be connected to with the supplied credentials.",
        "Asset": "10.15.0.145",
        "Status": "IN RETEST",
        "Severity": "LOW",
        "Responsible": "Diego",
        "Port": 445,
        "Protocol": "tcp",
        "ServiceName": "cifs",
        "Source": "SCAN",
        "ChangedDate": "11/07/2018-19:31:14",
        "LastSeenDate": "08/06/2016-20:28:45",
        "DueDate": "07/02/2019-23:00:07",
        "Tags": "Microsoft",
        "KB": "Microsoft Windows SMB Registry : Nessus Cannot Access the Windows Registry",
        "Recommendations": "",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37048,
        "Name": "SSL Certificate Cannot Be Trusted",
        "Description": "\\nThe server's X.509 certificate cannot be trusted. This situation can occur in three different ways in which the chain of trust can be broken as stated below :\\n\\n  - First the top of the certificate chain sent by the     server might not be descended from a known public     certificate authority. This can occur either when the     top of the chain is an unrecognized self-signed     certificate or when intermediate certificates are     missing that would connect the top of the certificate     chain to a known public certificate authority.\\n\\n  - Second the certificate chain may contain a certificate     that is not valid at the time of the scan. This can     occur either when the scan occurs before one of the     certificate's 'notBefore' dates or after one of the     certificate's 'notAfter' dates.\\n\\n  - Third the certificate chain may contain a signature     that either didn't match the certificate's information     or could not be verified. Bad signatures can be fixed by     getting the certificate with the bad signature to be     re-signed by its issuer. Signatures that could not be     verified are the result of the certificate's issuer     using a signing algorithm that Nessus either does not     support or does not recognize.\\n\\nIf the remote host is a public host in production any break in the chain makes it more difficult for users to verify the authenticity and identity of the web server. This could make it easier to carry out man-in-the-middle attacks against the remote host.",
        "Asset": "10.15.0.126",
        "Status": "PENDING",
        "Severity": "INFORMATIVE",
        "Responsible": "Thiago",
        "Port": 3389,
        "Protocol": "tcp",
        "ServiceName": "msrdp",
        "Source": "SCAN",
        "ChangedDate": "11/01/2018-19:31:15",
        "LastSeenDate": "08/06/2016-19:44:25",
        "DueDate": "17/01/2019-23:00:08",
        "Tags": "SSL",
        "KB": "SSL Certificate Cannot Be Trusted",
        "Recommendations": "\\nPurchase or generate a proper certificate for this service.\\n",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37047,
        "Name": "SSL Certificate Cannot Be Trusted",
        "Description": "\\nThe server's X.509 certificate cannot be trusted. This situation can occur in three different ways in which the chain of trust can be broken as stated below :\\n\\n  - First the top of the certificate chain sent by the     server might not be descended from a known public     certificate authority. This can occur either when the     top of the chain is an unrecognized self-signed     certificate or when intermediate certificates are     missing that would connect the top of the certificate     chain to a known public certificate authority.\\n\\n  - Second the certificate chain may contain a certificate     that is not valid at the time of the scan. This can     occur either when the scan occurs before one of the     certificate's 'notBefore' dates or after one of the     certificate's 'notAfter' dates.\\n\\n  - Third the certificate chain may contain a signature     that either didn't match the certificate's information     or could not be verified. Bad signatures can be fixed by     getting the certificate with the bad signature to be     re-signed by its issuer. Signatures that could not be     verified are the result of the certificate's issuer     using a signing algorithm that Nessus either does not     support or does not recognize.\\n\\nIf the remote host is a public host in production any break in the chain makes it more difficult for users to verify the authenticity and identity of the web server. This could make it easier to carry out man-in-the-middle attacks against the remote host.",
        "Asset": "10.15.0.15",
        "Status": "IN TREATMENT",
        "Severity": "HIGH",
        "Responsible": "Fernanda",
        "Port": 3389,
        "Protocol": "tcp",
        "ServiceName": "msrdp",
        "Source": "SCAN",
        "ChangedDate": "11/11/2018-19:31:16",
        "LastSeenDate": "08/06/2016-14:20:00",
        "DueDate": "17/01/2019-23:00:09",
        "Tags": "SSL",
        "KB": "SSL Certificate Cannot Be Trusted",
        "Recommendations": "\\nPurchase or generate a proper certificate for this service.\\n",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37046,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.40",
        "Status": "NON EXISTENT",
        "Severity": "MEDIUM",
        "Responsible": "Raphael Pinheiro",
        "Port": 3389,
        "Protocol": "tcp",
        "ServiceName": "msrdp",
        "Source": "SCAN",
        "ChangedDate": "11/06/2018-19:31:17",
        "LastSeenDate": "08/06/2016-15:49:33",
        "DueDate": "17/01/2019-23:00:10",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37045,
        "Name": "Microsoft Windows SMB Service Detection",
        "Description": "\\nThe remote service understands the CIFS (Common Internet File System) or Server Message Block (SMB) protocol used to provide shared access to files printers etc between nodes on a network.",
        "Asset": "10.15.0.45",
        "Status": "ACCEPTED",
        "Severity": "LOW",
        "Responsible": "Starlin",
        "Port": 139,
        "Protocol": "tcp",
        "ServiceName": "smb",
        "Source": "SCAN",
        "ChangedDate": "21/01/2018-19:31:18",
        "LastSeenDate": "08/06/2016-16:08:15",
        "DueDate": "17/01/2019-23:00:11",
        "Tags": "Microsoft; SMB",
        "KB": "Microsoft Windows SMB Service Detection",
        "Recommendations": "",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37044,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.19",
        "Status": "REOPENED",
        "Severity": "MEDIUM",
        "Responsible": "Raphael Pinheiro",
        "Port": 80,
        "Protocol": "tcp",
        "ServiceName": "www",
        "Source": "SCAN",
        "ChangedDate": "12/01/2018-19:31:19",
        "LastSeenDate": "08/06/2016-14:44:25",
        "DueDate": "17/01/2019-23:00:12",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37043,
        "Name": "SSL Certificate Information",
        "Description": "\\nThis plugin connects to every SSL-related port and attempts to extract and dump the X.509 certificate.",
        "Asset": "10.15.0.133",
        "Status": "IN RETEST",
        "Severity": "CRITICAL",
        "Responsible": "Starlin",
        "Port": 48007,
        "Protocol": "tcp",
        "ServiceName": "unknown",
        "Source": "SCAN",
        "ChangedDate": "01/01/2018-19:31:20",
        "LastSeenDate": "08/06/2016-20:33:03",
        "DueDate": "17/01/2019-23:00:13",
        "Tags": "SSL",
        "KB": "SSL Certificate Information",
        "Recommendations": "",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37042,
        "Name": "Service Detection",
        "Description": "\\nNessus was able to identify the remote service by its banner or by looking at the error message it sends when it receives an HTTP request.",
        "Asset": "10.15.0.23",
        "Status": "NON EXISTENT",
        "Severity": "HIGH",
        "Responsible": "Starlin",
        "Port": 3872,
        "Protocol": "tcp",
        "ServiceName": "www",
        "Source": "SCAN",
        "ChangedDate": "11/03/2018-19:31:21",
        "LastSeenDate": "08/06/2016-22:08:39",
        "DueDate": "17/01/2019-23:00:14",
        "Tags": "Service",
        "KB": "Service Detection",
        "Recommendations": "",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37041,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.15",
        "Status": "ACCEPTED",
        "Severity": "INFORMATIVE",
        "Responsible": "Starlin",
        "Port": 135,
        "Protocol": "tcp",
        "ServiceName": "epmap",
        "Source": "SCAN",
        "ChangedDate": "11/05/2018-19:31:22",
        "LastSeenDate": "08/06/2016-14:20:00",
        "DueDate": "11/03/2019-23:00:15",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37040,
        "Name": "SSL Certificate Cannot Be Trusted",
        "Description": "\\nThe server's X.509 certificate cannot be trusted. This situation can occur in three different ways in which the chain of trust can be broken as stated below :\\n\\n  - First the top of the certificate chain sent by the     server might not be descended from a known public     certificate authority. This can occur either when the     top of the chain is an unrecognized self-signed     certificate or when intermediate certificates are     missing that would connect the top of the certificate     chain to a known public certificate authority.\\n\\n  - Second the certificate chain may contain a certificate     that is not valid at the time of the scan. This can     occur either when the scan occurs before one of the     certificate's 'notBefore' dates or after one of the     certificate's 'notAfter' dates.\\n\\n  - Third the certificate chain may contain a signature     that either didn't match the certificate's information     or could not be verified. Bad signatures can be fixed by     getting the certificate with the bad signature to be     re-signed by its issuer. Signatures that could not be     verified are the result of the certificate's issuer     using a signing algorithm that Nessus either does not     support or does not recognize.\\n\\nIf the remote host is a public host in production any break in the chain makes it more difficult for users to verify the authenticity and identity of the web server. This could make it easier to carry out man-in-the-middle attacks against the remote host.",
        "Asset": "10.15.0.23",
        "Status": "PENDING",
        "Severity": "INFORMATIVE",
        "Responsible": "",
        "Port": 4903,
        "Protocol": "tcp",
        "ServiceName": "www",
        "Source": "CHECKLIST",
        "ChangedDate": "11/01/2018-19:31:23",
        "LastSeenDate": "08/06/2016-22:08:39",
        "DueDate": "11/03/2019-23:00:16",
        "Tags": "SSL",
        "KB": "SSL Certificate Cannot Be Trusted",
        "Recommendations": "\\nPurchase or generate a proper certificate for this service.\\n",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37039,
        "Name": "SSL Certificate Information",
        "Description": "\\nThis plugin connects to every SSL-related port and attempts to extract and dump the X.509 certificate.",
        "Asset": "10.15.0.16",
        "Status": "PENDING",
        "Severity": "INFORMATIVE",
        "Responsible": "",
        "Port": 2381,
        "Protocol": "tcp",
        "ServiceName": "www",
        "Source": "CHECKLIST",
        "ChangedDate": "11/01/2018-19:31:24",
        "LastSeenDate": "08/06/2016-14:30:14",
        "DueDate": "11/03/2019-23:00:17",
        "Tags": "SSL",
        "KB": "SSL Certificate Information",
        "Recommendations": "",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37038,
        "Name": "HTTP Methods Allowed (per directory)",
        "Description": "\\nBy calling the OPTIONS method it is possible to determine which HTTP methods are allowed on each directory. \\n\\nAs this list may be incomplete the plugin also tests - if 'Thorough tests' are enabled or 'Enable web applications tests' is set to 'yes' in the scan policy - various known HTTP methods on each directory and considers them as unsupported if it receives a response code of 400 403 405 or 501. \\n\\nNote that the plugin output is only informational and does not necessarily indicate the presence of any security vulnerabilities.",
        "Asset": "10.15.0.111",
        "Status": "PENDING",
        "Severity": "INFORMATIVE",
        "Responsible": "",
        "Port": 2381,
        "Protocol": "tcp",
        "ServiceName": "www",
        "Source": "SCAN",
        "ChangedDate": "19/07/2018-19:31:25",
        "LastSeenDate": "08/06/2016-18:36:55",
        "DueDate": "11/03/2019-23:00:18",
        "Tags": "HTTP",
        "KB": "HTTP Methods Allowed (per directory)",
        "Recommendations": "",
        "RootCause": "Generic  ",
        
    },
    {
        "ID": 37037,
        "Name": "Nessus SYN scanner",
        "Description": "\\nThis plugin is a SYN 'half-open' port scanner.  It shall be reasonably quick even against a firewalled target. \\n\\nNote that SYN scans are less intrusive than TCP (full connect) scans against broken services but they might cause problems for less robust firewalls and also leave unclosed connections on the remote target if the network is loaded.",
        "Asset": "10.15.0.124",
        "Status": "PENDING",
        "Severity": "INFORMATIVE",
        "Responsible": "",
        "Port": 135,
        "Protocol": "tcp",
        "ServiceName": "epmap",
        "Source": "SCAN",
        "ChangedDate": "17/01/2018-19:31:26",
        "LastSeenDate": "08/06/2016-19:34:56",
        "DueDate": "11/03/2019-23:00:19",
        "Tags": "SYN; NESSUS",
        "KB": "Nessus SYN scanner",
        "Recommendations": "\\nProtect your target with an IP filter.\\n",
        "RootCause": "Generic  ",
        
    }
];

export default gatJson;
